### ISSUE TITLE
Camera image is not rendered properly upon rotation (Android)

### ISSUE THREAD

**Issue by DK15** [yershalom/reddit_flutter#2]
If you capture an image from Android emulator and try to rotate it, the app throws renderflow exception at the bottom of the screen, as below:

![screen shot 2019-01-13 at 11 09 02 pm](https://user-images.githubusercontent.com/16548367/51088702-1ada8e00-1789-11e9-8819-01472a7b5ab2.png)

Note that, since we can't access camera on ios simulator, I couldn't verify if this issue occurs there as well.

I've a fix for this issue. @yershalom do you mind if I open a pull request to fix this issue ?

**Comment by yershalom** [comment]
You are more than welcome to add a PR.
When you'll have a pr I'll test it on iOS
